# OWASP ZAP API Scan
# https://github.com/marketplace/actions/owasp-zap-api-scan

name: OWASP ZAP API Scan
on:
  workflow_dispatch:
jobs:
  zap_scan:
    runs-on: ubuntu-latest  
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: main
      - name: ZAP Scan
        uses: zaproxy/action-api-scan@v0.1.0
        with:
          target: 'openapi.yaml'
